// tests/fixtures/meshes/regen.test.ts
//
// Fixture regeneration + verification contract for issue #8.
//
// Two modes:
//
//   1. Default (`pnpm test`): read the three committed STL+JSON fixtures and
//      assert that re-running the generator in-memory produces byte-identical
//      STL bytes, byte-identical sidecar JSON text, and that the sidecar
//      values match what the loader reports. Any drift hard-fails CI.
//
//   2. Regen (`pnpm test:fixtures-regen`): write the generated bytes to disk
//      before the verification pass. On a clean checkout this leaves
//      `git diff` empty (determinism contract, CLAUDE.md hard requirement).
//      If anyone ever wants to intentionally update a fixture, they must run
//      this command and review the diff before committing.
//
// This file is the only place that exercises `regenerateAllFixtures()`.

import { createHash } from 'node:crypto';
import { readFileSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { beforeAll, describe, expect, test } from 'vitest';
import {
  FIXTURES,
  generateAllFixtureBundles,
  generateFixtureBundle,
  isWatertightManifold,
  meshSurfaceArea,
  meshVolume,
  regenerateAllFixtures,
  type FixtureBundle,
} from './generate';
import { loadFixture } from './loader';

const FIXTURE_DIR = dirname(fileURLToPath(import.meta.url));
const REGEN = process.env.REGEN_FIXTURES === '1';
const MAX_FIXTURE_BYTES = 100 * 1024; // AC: "< 100 KB"

function sha256(bytes: Uint8Array | Buffer): string {
  return createHash('sha256').update(bytes).digest('hex');
}

let bundlesByName = new Map<string, FixtureBundle>();

beforeAll(() => {
  if (REGEN) {
    regenerateAllFixtures();
  }
  bundlesByName = new Map(
    generateAllFixtureBundles().map((b) => [b.name, b] as const),
  );
});

describe('procedural fixture generator — byte stability', () => {
  test('regeneration is idempotent across two successive in-memory runs', () => {
    // Guards against latent non-determinism in the generator itself:
    // if build() is not pure, two runs would diverge before we even write
    // to disk. Catching this here gives a clearer failure signal than a
    // `git diff` after `test:fixtures-regen`.
    const run1 = generateAllFixtureBundles();
    const run2 = generateAllFixtureBundles();
    expect(run1.length).toBe(run2.length);
    for (let i = 0; i < run1.length; i++) {
      const a = run1[i]!;
      const b = run2[i]!;
      expect(a.name).toBe(b.name);
      expect(sha256(a.stlBytes)).toBe(sha256(b.stlBytes));
      expect(a.sidecarJson).toBe(b.sidecarJson);
    }
  });

  for (const desc of FIXTURES) {
    describe(desc.name, () => {
      test(`committed STL matches generator (SHA-256) — ${desc.name}`, () => {
        const bundle = bundlesByName.get(desc.name)!;
        const onDisk = readFileSync(join(FIXTURE_DIR, `${desc.name}.stl`));
        const expected = sha256(bundle.stlBytes);
        const actual = sha256(onDisk);
        if (expected !== actual) {
          throw new Error(
            [
              `Committed fixture ${desc.name}.stl is out of sync with the generator.`,
              `  committed SHA: ${actual}`,
              `  generated SHA: ${expected}`,
              `  Run \`pnpm test:fixtures-regen\` and review the diff.`,
            ].join('\n'),
          );
        }
      });

      test(`committed sidecar JSON matches generator — ${desc.name}`, () => {
        const bundle = bundlesByName.get(desc.name)!;
        const onDisk = readFileSync(
          join(FIXTURE_DIR, `${desc.name}.json`),
          'utf8',
        );
        if (onDisk !== bundle.sidecarJson) {
          throw new Error(
            [
              `Committed sidecar ${desc.name}.json is out of sync with the generator.`,
              `  Run \`pnpm test:fixtures-regen\` and review the diff.`,
            ].join('\n'),
          );
        }
      });

      test(`fixture size is under 100 KB — ${desc.name}`, () => {
        const stat = statSync(join(FIXTURE_DIR, `${desc.name}.stl`));
        expect(stat.size).toBeLessThan(MAX_FIXTURE_BYTES);
      });

      test(`expected triangle count — ${desc.name}`, () => {
        const bundle = bundlesByName.get(desc.name)!;
        expect(bundle.mesh.triangles.length / 3).toBe(desc.expectedTriCount);
      });

      test(`loader reads the fixture back consistently — ${desc.name}`, async () => {
        const loaded = await loadFixture(desc.name);
        expect(loaded.meta.name).toBe(desc.name);
        expect(loaded.geometry.triCount).toBe(desc.expectedTriCount);
        expect(loaded.meta.triCount).toBe(desc.expectedTriCount);
      });

      test(`sidecar values match the actual mesh — ${desc.name}`, async () => {
        const loaded = await loadFixture(desc.name);
        const bundle = bundlesByName.get(desc.name)!;
        // Volume + area recomputed from the raw mesh in memory. Use the
        // same rounded precision as the sidecar.
        const vol = meshVolume(bundle.mesh);
        const area = meshSurfaceArea(bundle.mesh);
        expect(loaded.meta.volume_mm3).toEqualWithTolerance(vol, {
          abs: 1e-5,
          rel: 1e-5,
        });
        expect(loaded.meta.surfaceArea_mm2).toEqualWithTolerance(area, {
          abs: 1e-5,
          rel: 1e-5,
        });
        // Bounding box: loader trusts the sidecar, so compare sidecar
        // against in-memory AABB of the parsed STL geometry.
        const positions = loaded.geometry.positions;
        let minX = Infinity,
          minY = Infinity,
          minZ = Infinity;
        let maxX = -Infinity,
          maxY = -Infinity,
          maxZ = -Infinity;
        for (let i = 0; i < positions.length; i += 3) {
          const x = positions[i]!;
          const y = positions[i + 1]!;
          const z = positions[i + 2]!;
          if (x < minX) minX = x;
          if (y < minY) minY = y;
          if (z < minZ) minZ = z;
          if (x > maxX) maxX = x;
          if (y > maxY) maxY = y;
          if (z > maxZ) maxZ = z;
        }
        expect(loaded.meta.boundingBoxMin).toEqualWithTolerance(
          [minX, minY, minZ],
          // 1e-5 mm canonicalisation quantisation + 1e-6 sidecar rounding.
          { abs: 2e-5 },
        );
        expect(loaded.meta.boundingBoxMax).toEqualWithTolerance(
          [maxX, maxY, maxZ],
          { abs: 2e-5 },
        );
      });
    });
  }
});

describe('procedural fixture generator — per-fixture semantics', () => {
  test('unit-cube volume is 1.0 mm³ to 1e-6', () => {
    const bundle = generateFixtureBundle(FIXTURES[0]!);
    expect(meshVolume(bundle.mesh)).toEqualWithTolerance(1.0, { abs: 1e-6 });
    // Surface area sanity: 6 × 1² = 6.0
    expect(meshSurfaceArea(bundle.mesh)).toEqualWithTolerance(6.0, {
      abs: 1e-6,
    });
    // Exact bounds.
    expect(bundle.sidecar.boundingBoxMin).toEqual([-0.5, -0.5, -0.5]);
    expect(bundle.sidecar.boundingBoxMax).toEqual([0.5, 0.5, 0.5]);
  });

  test('unit-sphere-icos-3 volume is within 2% of 4/3·π', () => {
    const bundle = generateFixtureBundle(FIXTURES[1]!);
    const trueVol = (4 / 3) * Math.PI;
    const actual = meshVolume(bundle.mesh);
    const relErr = Math.abs(actual - trueVol) / trueVol;
    expect(relErr).toBeLessThan(0.02);
    // Sidecar documents the *actual* (rounded) value per README contract.
    expect(bundle.sidecar.volume_mm3).toBeCloseTo(actual, 5);
    // Icosphere is watertight + manifold.
    expect(isWatertightManifold(bundle.mesh)).toBe(true);
  });

  test('torus-32x16 is watertight (genus-1 topology)', () => {
    const bundle = generateFixtureBundle(FIXTURES[2]!);
    expect(isWatertightManifold(bundle.mesh)).toBe(true);
    // Genus-1 sanity: V - E + F = 0 for a torus.
    // We have 32 × 16 = 512 vertices (no seam duplication), 1024 faces,
    // and each triangle contributes 3 half-edges -> 3 × 1024 / 2 = 1536 edges.
    const V = bundle.mesh.vertices.length / 3;
    const F = bundle.mesh.triangles.length / 3;
    const E = (3 * F) / 2;
    expect(V - E + F).toBe(0);
    expect(V).toBe(512);
    expect(F).toBe(1024);
    // Volume near analytic 2·π²·R·r² = 2·π²·1·0.09 ≈ 1.77653. The 32×16
    // tessellation is coarse enough that the lower-bound polygonal volume
    // lands about 3% under the analytic value — tolerate 5% so the
    // assertion is a sanity check, not a tessellation-density spec.
    const trueVol = 2 * Math.PI ** 2 * 1 * 0.3 ** 2;
    const relErr = Math.abs(meshVolume(bundle.mesh) - trueVol) / trueVol;
    expect(relErr).toBeLessThan(0.05);
  });
});
